version: '3' # Indecates Docker-Compose file is using Version 3 file
services: # Service List
  server: # Main service
    build:
      context: .
      dockerfile: solais/Dockerfile
    ports:
      - '9000:9000'
    links:
      - redis_master
      - slave6380
  redis_master: # Master Redis Servie
    # image: redis:latest
    build:
      context: .
      dockerfile: redis/Dockerfile
    container_name: master
    ports:
      - '6379:6379'
    restart: always
    expose:
      - 6379
  slave6380:
    image: redis:latest
    container_name: slave01
    ports:
      - '6380:6379'
    restart: always
    expose:
      - 6379
    command: /bin/bash -c "sleep 2 && redis-server --port 6380 --slaveof redis_master 6379"
    depends_on:
      - redis_master
